volumes:
  pgdata:
  static_files:
services:
  python:
    #image: python:3.8.10
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    volumes:
      - ./backend:/app
      - static_files:/static_files
    ports:
      - 8000:8000
    command: gunicorn -w 4 root.wsgi -b 0.0.0.0:8000
  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_USER: boiler
      POSTGRES_DB: boiler
      POSTGRES_PASSWORD: boiler
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 8080:80
